FROM rabbitmq:3-management

EXPOSE 5672 15672

ENV RABBITMQ_DEFAULT_USER=${RABBITMQ_USER:-guest}
ENV RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS:-guest}

HEALTHCHECK --interval=30s --timeout=10s --retries=5 \
  CMD rabbitmq-diagnostics check_port_connectivity